apiVersion: v1
kind: Secret
metadata:
  name: "user-service-secret"
type: Opaque
data:
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
