version: '3'

services:
  order_db:
    image: postgres
    container_name: order-db
    volumes:
      - order_db:/var/lib/postgresql/data
      - ./migrations/create_order_table.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .local.env
    networks:
      - order-network
    ports:
      - "5433:5432"

networks:
  order-network:
    driver: bridge

volumes:
  order_db: