version: '3'

services: 
    user_db:
        image: postgres
        container_name: user-db
        volumes: 
            - db:/var/lib/postgresql/data
            - ./migrations/create_users_table.sql:/docker-entrypoint-initdb.d/init.sql
        environment: 
            - POSTGRES_DB=user_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        env_file: 
            - .local.env
        networks: 
            - mynet
        ports: 
            - "5432:5432"
networks:
    mynet:
        driver: bridge

volumes:
    db: