{
 "title": "User service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m]))"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(nginx_ingress_controller_requests{status=\"500\"}[1m]))) / sum(rate(nginx_ingress_controller_requests[1m]))"
    }
   ]
  },
  {
   "title": "k8s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "User service pods' cpu usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum (rate(container_cpu_usage_seconds_total{container=\"user-service\"}[1m]) > 0) / sum (container_spec_cpu_quota{container=\"user-service\"} > 0)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "User service pods' memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{container=\"user-service\"}) / 1000000",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "User service API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "API RPS",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, url) (rate(api_requests_total{}[1m]))",
     "legendFormat": "{{ method }} {{ url }}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (method, url, le) (rate(http_response_time_seconds_bucket[1m]))) * 1000",
     "legendFormat": "P99 {{ method }} {{ url }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (method, url, le) (rate(http_response_time_seconds_bucket[1m]))) * 1000",
     "legendFormat": "P95 {{ method }} {{ url }}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (method, url, le) (rate(http_response_time_seconds_bucket[1m]))) * 1000",
     "legendFormat": "P50 {{ method }} {{ url }}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "(sum by (method, url) (rate(api_requests_total{code=\"500\"}[1m]))) / (sum by (method, url) (rate(api_requests_total[1m])))",
     "legendFormat": "{{ method }} {{ url }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"user-db\"}[1m])) / sum(container_spec_cpu_quota{container=\"user-db\"})"
    }
   ]
  },
  {
   "title": "RAM saturation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(namespace,pod,container)(kube_pod_container_resource_limits{resource=\"memory\", container=\"user-db\"}) - sum by(namespace,pod,container)(container_memory_usage_bytes{container=\"user-db\"})) / 1000000\n"
    }
   ]
  },
  {
   "title": "In-memory transaction rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (rate(pg_stat_database_blks_hit{datname=\"user-db\"}[2m]) /\n((rate(pg_stat_database_blks_hit{datname=\"user-db\"}[2m]) +\nrate(pg_stat_database_blks_read{datname=\"user-db\"}[2m]))>0))",
     "legendFormat": "{{ Database }}"
    }
   ]
  }
 ]
}