apiVersion: v1
kind: Secret
metadata:
  name: "order-service-secret"
type: Opaque
data:
  ORDER_DB_URL: {{ printf "jdbc:postgresql://%s:%s/%s" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
  ORDER_DB_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  ORDER_DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  BILLING_URL: {{ .Values.billing.url | b64enc | quote }}
  BILLING_PORT: {{ .Values.billing.port | b64enc | quote }}