version: '3'

services:
  billing_db:
    image: postgres
    container_name: billing-db
    volumes:
      - billing_db:/var/lib/postgresql/data
      - ./migrations/create_billing_accounts_table.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=billing_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .local.env
    networks:
      - billing-network
    ports:
      - "5432:5432"

networks:
  billing-network:
    driver: bridge

volumes:
  billing_db:
